// src/components/layout/AppBar.tsx
import { Bell, Search, Sparkles, Home } from 'lucide-react';
import { Button } from '../ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../ui/select';
import { Badge } from '../ui/badge';
import { Entity, GlobalFilters, TenantDirectoryEntry } from '../../types';
import { mockPeriods } from '../../lib/mockData';
import { cn } from '../ui/utils';

interface AppBarProps {
  filters: GlobalFilters;
  onFiltersChange: (filters: GlobalFilters) => void;
  tenantOptions: TenantDirectoryEntry[];
  tenantLoading: boolean;
  entityOptions: Entity[];
  onTenantChange: (tenantId: number) => void;
  unreadAlerts: number;
  onAlertsClick: () => void;
  aiEnabled: boolean;
  onAiToggle: () => void;
  onSearchClick: () => void;
  currentPage: string;
  onNavigate: (page: string) => void;
}

const topNavItems = [
  { id: 'overview', label: 'Dashboard' },
  { id: 'reports', label: 'Reports' },
  { id: 'compare', label: 'Compare' },
  { id: 'alerts', label: 'Alerts' },
];

export function AppBar({
  filters,
  onFiltersChange,
  tenantOptions,
  tenantLoading,
  entityOptions,
  onTenantChange,
  unreadAlerts,
  onAlertsClick,
  aiEnabled,
  onAiToggle,
  onSearchClick,
  currentPage,
  onNavigate,
}: AppBarProps) {
  return (
    <div className="border-b bg-white">
      {/* Top navigation bar */}
      <div className="flex items-center justify-between border-b px-6 py-3">
        {/* Left: Logo and main navigation */}
        <div className="flex items-center gap-6">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded bg-primary">
              <Home className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="text-primary">ERP</span>
          </div>

          {/* Horizontal navigation */}
          <nav className="flex items-center gap-1">
            {topNavItems.map((item) => (
              <button
                key={item.id}
                onClick={() => onNavigate(item.id)}
                className={cn(
                  'px-4 py-2 transition-colors',
                  currentPage === item.id
                    ? 'text-primary'
                    : 'text-muted-foreground hover:text-foreground'
                )}
              >
                {item.label}
                {item.id === 'alerts' && unreadAlerts > 0 && (
                  <Badge variant="destructive" className="ml-2 h-5 min-w-5 px-1">
                    {unreadAlerts}
                  </Badge>
                )}
              </button>
            ))}
          </nav>
        </div>

        {/* Right: Actions */}
        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="icon"
            onClick={onSearchClick}
            title="Search (Press /)"
          >
            <Search className="h-4 w-4" />
          </Button>

          <Button
            variant="ghost"
            size="icon"
            onClick={onAlertsClick}
            className="relative"
          >
            <Bell className="h-4 w-4" />
            {unreadAlerts > 0 && (
              <Badge
                variant="destructive"
                className="absolute -right-1 -top-1 h-4 min-w-4 px-1"
              >
                {unreadAlerts}
              </Badge>
            )}
          </Button>

          <Button
            variant={aiEnabled ? 'default' : 'ghost'}
            size="sm"
            onClick={onAiToggle}
            className="gap-2"
          >
            <Sparkles className="h-4 w-4" />
            AI Explain
          </Button>
        </div>
      </div>

      {/* Second row: Filters */}
      <div className="flex items-center gap-3 px-6 py-2">
        {/* Tenant */}
        <div className="flex items-center gap-2">
          <span className="text-muted-foreground">Tenant:</span>
          <Select
            value={filters.tenant ? String(filters.tenant.id) : undefined}
            onValueChange={(value) => onTenantChange(Number(value))}
            disabled={tenantLoading || tenantOptions.length === 0}
          >
            <SelectTrigger className="w-[200px]">
              <SelectValue
                placeholder={
                  tenantLoading ? 'Loading tenants...' : 'Select tenant'
                }
              />
            </SelectTrigger>
            <SelectContent>
              {tenantOptions.map((tenant) => (
                <SelectItem
                  key={tenant.tenant_id}
                  value={tenant.tenant_id.toString()}
                >
                  {tenant.tenant_name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Entity */}
        <div className="flex items-center gap-2">
          <span className="text-muted-foreground">Entity:</span>
          <Select
            value={filters.entity?.id}
            onValueChange={(value) => {
              const entity = entityOptions.find((e) => e.id === value);
              if (entity) onFiltersChange({ ...filters, entity });
            }}
            disabled={entityOptions.length === 0}
          >
            <SelectTrigger className="w-[180px]">
              <SelectValue
                placeholder={
                  entityOptions.length === 0
                    ? 'No entities'
                    : 'Select entity'
                }
              />
            </SelectTrigger>
            <SelectContent>
              {entityOptions.map((entity) => (
                <SelectItem key={entity.id} value={entity.id}>
                  {entity.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Period */}
        <Select
          value={filters.period.id}
          onValueChange={(value) => {
            const period = mockPeriods.find((p) => p.id === value);
            if (period) onFiltersChange({ ...filters, period });
          }}
        >
          <SelectTrigger className="w-[140px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {mockPeriods.map((period) => (
              <SelectItem key={period.id} value={period.id}>
                {period.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>
    </div>
  );
}

// src/app/layout/app-bar/app-bar.component.ts
import { CommonModule } from '@angular/common';
import { Component, HostListener, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IsActiveMatchOptions,
  Router,
  RouterModule,
} from '@angular/router';
import { mockPeriods } from '../../data/mock-data';
import { DashboardStateService } from '../../core/services/dashboard-state.service';
import { LucideIconsModule } from '../../shared/lucide-icons.module';

@Component({
  selector: 'app-app-bar',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, LucideIconsModule],
  templateUrl: './app-bar.component.html',
  styleUrl: './app-bar.component.scss',
})
export class AppBarComponent {
  protected readonly periods = mockPeriods;
  protected readonly topNav = [
    { id: 'overview', label: 'Dashboard', path: '/overview' },
    { id: 'reports', label: 'Reports', path: '/reports' },
    { id: 'compare', label: 'Compare', path: '/compare' },
    { id: 'alerts', label: 'Alerts', path: '/alerts' },
  ];

  private readonly router = inject(Router);
  protected readonly state = inject(DashboardStateService);
  private readonly activeMatch: IsActiveMatchOptions = {
    paths: 'exact',
    queryParams: 'ignored',
    fragment: 'ignored',
    matrixParams: 'ignored',
  };

  @HostListener('document:keydown', ['$event'])
  handleKeyboardShortcut(event: KeyboardEvent): void {
    if (event.key === '/' && !event.metaKey && !event.ctrlKey) {
      event.preventDefault();
      this.openSearch();
    }
  }

  protected openSearch(): void {
    this.state.setSearchOpen(true);
  }

  protected navigate(path: string): void {
    this.state.navigateTo(path);
  }

  protected toggleAi(): void {
    this.state.toggleAiInsights();
  }

  protected isActive(path: string): boolean {
    return this.router.isActive(path, this.activeMatch);
  }

  protected onTenantChange(value: string): void {
    const tenantId = Number(value);
    if (!Number.isNaN(tenantId)) {
      this.state.setTenant(tenantId);
    }
  }

  protected onEntityChange(value: string): void {
    this.state.setEntity(value);
  }

  protected onPeriodChange(value: string): void {
    this.state.setPeriod(value);
  }
}

<header class="border-b bg-white">
  <div class="flex items-center justify-between border-b px-6 py-3">
    <div class="flex items-center gap-6">
      <button
        class="flex items-center gap-2 rounded px-2 py-1 text-primary transition hover:bg-primary/10"
        type="button"
        (click)="navigate('/overview')"
      >
        <div class="flex h-8 w-8 items-center justify-center rounded bg-primary">
          <lucide-icon name="Home" class="h-5 w-5 text-white" />
        </div>
        <span class="font-semibold">ERP</span>
      </button>

      <nav class="flex items-center gap-1 text-sm font-medium">
        @for (item of topNav; track item.id) {
          <button
            type="button"
            (click)="navigate(item.path)"
            class="rounded px-4 py-2 transition-colors"
            [ngClass]="
              isActive(item.path)
                ? 'text-primary'
                : 'text-muted-foreground hover:text-foreground'
            "
          >
            <span>{{ item.label }}</span>
            @if (item.id === 'alerts' && state.unreadAlerts() > 0) {
              <span
                class="ml-2 inline-flex h-5 min-w-5 items-center justify-center rounded-full bg-red-500 px-1 text-xs text-white"
              >
                {{ state.unreadAlerts() }}
              </span>
            }
          </button>
        }
      </nav>
    </div>

    <div class="flex items-center gap-2">
      <button
        type="button"
        class="flex h-9 w-9 items-center justify-center rounded-full text-muted-foreground transition hover:bg-muted"
        (click)="openSearch()"
        title="Search (Press /)"
      >
        <lucide-icon name="Search" class="h-4 w-4" />
      </button>
      <button
        type="button"
        class="relative flex h-9 w-9 items-center justify-center rounded-full text-muted-foreground transition hover:bg-muted"
        (click)="navigate('/alerts')"
        title="Alerts"
      >
        <lucide-icon name="Bell" class="h-4 w-4" />
        @if (state.unreadAlerts() > 0) {
          <span
            class="absolute -right-1 -top-1 inline-flex h-4 min-w-4 items-center justify-center rounded-full bg-red-500 px-1 text-[10px] text-white"
          >
            {{ state.unreadAlerts() }}
          </span>
        }
      </button>
      <button
        type="button"
        class="flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-medium transition"
        [ngClass]="
          state.aiEnabled()
            ? 'bg-primary text-white'
            : 'text-muted-foreground hover:bg-muted'
        "
        (click)="toggleAi()"
      >
        <lucide-icon name="Sparkles" class="h-4 w-4" />
        AI Explain
      </button>
    </div>
  </div>

  <div class="flex flex-wrap items-center gap-3 px-6 py-2 text-sm">
    <div class="flex items-center gap-2">
      <span class="text-muted-foreground">Tenant:</span>
      <select
        class="w-48 rounded border border-border bg-input-background px-3 py-1.5 text-sm"
        [disabled]="state.tenantLoading() || !state.tenantDirectory().length"
        [ngModel]="state.filters().tenant?.id"
        (ngModelChange)="onTenantChange($event)"
      >
        @if (state.tenantLoading()) {
          <option selected>Loading tenants...</option>
        } @else {
          <option [ngValue]="undefined">Select tenant</option>
          @for (tenant of state.tenantDirectory(); track tenant.tenant_id) {
            <option [ngValue]="tenant.tenant_id">
              {{ tenant.tenant_name }}
            </option>
          }
        }
      </select>
    </div>

    <div class="flex items-center gap-2">
      <span class="text-muted-foreground">Entity:</span>
      <select
        class="w-44 rounded border border-border bg-input-background px-3 py-1.5 text-sm"
        [disabled]="!state.entityOptions().length"
        [ngModel]="state.filters().entity?.id"
        (ngModelChange)="onEntityChange($event)"
      >
        @if (!state.entityOptions().length) {
          <option selected>No entities</option>
        } @else {
          @for (entity of state.entityOptions(); track entity.id) {
            <option [ngValue]="entity.id">{{ entity.name }}</option>
          }
        }
      </select>
    </div>

    <div class="flex items-center gap-2">
      <span class="text-muted-foreground">Period:</span>
      <select
        class="w-40 rounded border border-border bg-input-background px-3 py-1.5 text-sm"
        [ngModel]="state.filters().period.id"
        (ngModelChange)="onPeriodChange($event)"
      >
        @for (period of periods; track period.id) {
          <option [ngValue]="period.id">{{ period.label }}</option>
        }
      </select>
    </div>
  </div>
</header>
