// src/components/layout/Sidebar.tsx
import {
  LayoutDashboard,
  Droplets,
  ArrowDownToLine,
  ArrowUpToLine,
  TrendingUp,
  Repeat,
  DollarSign,
  Coins,
  FileText,
  Scale,
  Target,
  Settings,
  ChevronLeft,
  Home,
} from 'lucide-react';
import { cn } from '../ui/utils';
import { Button } from '../ui/button';
import { useState } from 'react';

interface SidebarProps {
  currentPage: string;
  onNavigate: (page: string) => void;
  userRole?: 'admin' | 'user';
}

const iconMap: Record<string, any> = {
  Home,
  Droplets,
  ArrowDownToLine,
  ArrowUpToLine,
  TrendingUp,
  Repeat,
  DollarSign,
  Coins,
  FileText,
  Scale,
  Target,
  Settings,
};

const sections = [
  { id: 'overview', name: 'Home', icon: 'Home' },
  { id: 'liquidity', name: 'Liquidity', icon: 'Droplets' },
  { id: 'ar', name: 'Incomes', icon: 'ArrowDownToLine' },
  { id: 'ap', name: 'Expenses', icon: 'ArrowUpToLine' },
  { id: 'profitability', name: 'Profitability', icon: 'TrendingUp' },
  { id: 'working-capital', name: 'Treasury', icon: 'Repeat' },
  { id: 'revenue-health', name: 'Revenue', icon: 'DollarSign' },
  { id: 'fx-treasury', name: 'FX & Treasury', icon: 'Coins' },
  { id: 'tax-vat', name: 'Files', icon: 'FileText' },
  { id: 'balance-sheet', name: 'Accounting', icon: 'Scale' },
  { id: 'concentration-risk', name: 'Master Data', icon: 'Target' },
];

export function Sidebar({ currentPage, onNavigate, userRole = 'user' }: SidebarProps) {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <div
      className={cn(
        'border-r bg-sidebar transition-all duration-300',
        collapsed ? 'w-16' : 'w-56'
      )}
    >
      {/* Collapse button */}
      <div className="flex items-center justify-end border-b p-3">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setCollapsed(!collapsed)}
          className="h-8 w-8"
        >
          <ChevronLeft
            className={cn(
              'h-4 w-4 transition-transform',
              collapsed && 'rotate-180'
            )}
          />
        </Button>
      </div>

      {/* Navigation */}
      <nav className="space-y-1 p-2">
        {sections.map((section) => {
          const Icon = iconMap[section.icon];
          const isActive = currentPage === section.id;

          return (
            <button
              key={section.id}
              onClick={() => onNavigate(section.id)}
              className={cn(
                'flex w-full items-center gap-3 rounded px-3 py-2 transition-colors',
                isActive
                  ? 'bg-sidebar-accent text-sidebar-accent-foreground'
                  : 'text-sidebar-foreground hover:bg-sidebar-accent/50'
              )}
            >
              <Icon className="h-4 w-4 shrink-0" />
              {!collapsed && <span className="truncate">{section.name}</span>}
            </button>
          );
        })}

        {/* Admin section */}
        {userRole === 'admin' && (
          <>
            <div className="my-2 h-px bg-sidebar-border" />
            <button
              onClick={() => onNavigate('ops-admin')}
              className={cn(
                'flex w-full items-center gap-3 rounded px-3 py-2 transition-colors',
                currentPage === 'ops-admin'
                  ? 'bg-sidebar-accent text-sidebar-accent-foreground'
                  : 'text-sidebar-foreground hover:bg-sidebar-accent/50'
              )}
            >
              <Settings className="h-4 w-4 shrink-0" />
              {!collapsed && <span className="truncate">Ops / Admin</span>}
            </button>
          </>
        )}
      </nav>
    </div>
  );
}

// src/app/layout/sidebar/sidebar.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import {
  IsActiveMatchOptions,
  Router,
  RouterModule,
} from '@angular/router';
import { DashboardStateService } from '../../core/services/dashboard-state.service';
import { LucideIconsModule } from '../../shared/lucide-icons.module';

interface NavItem {
  id: string;
  label: string;
  icon: string;
  path: string;
}

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideIconsModule],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.scss',
})
export class SidebarComponent {
  protected collapsed = signal(false);
  protected readonly items: NavItem[] = [
    { id: 'overview', label: 'Home', icon: 'Home', path: '/overview' },
    { id: 'liquidity', label: 'Liquidity', icon: 'Droplets', path: '/sections/liquidity' },
    { id: 'ar', label: 'Incomes', icon: 'ArrowDownToLine', path: '/sections/ar' },
    { id: 'ap', label: 'Expenses', icon: 'ArrowUpToLine', path: '/sections/ap' },
    { id: 'profitability', label: 'Profitability', icon: 'TrendingUp', path: '/sections/profitability' },
    { id: 'working-capital', label: 'Treasury', icon: 'Repeat', path: '/sections/working-capital' },
    { id: 'revenue-health', label: 'Revenue', icon: 'DollarSign', path: '/sections/revenue-health' },
    { id: 'fx-treasury', label: 'FX & Treasury', icon: 'Coins', path: '/sections/fx-treasury' },
    { id: 'tax-vat', label: 'Files', icon: 'FileText', path: '/sections/tax-vat' },
    { id: 'balance-sheet', label: 'Accounting', icon: 'Scale', path: '/sections/balance-sheet' },
    { id: 'concentration-risk', label: 'Master Data', icon: 'Target', path: '/sections/concentration-risk' },
  ];

  protected readonly adminItem: NavItem = {
    id: 'ops-admin',
    label: 'Ops / Admin',
    icon: 'Settings',
    path: '/ops',
  };

  private readonly router = inject(Router);
  protected readonly state = inject(DashboardStateService);
  private readonly activeMatch: IsActiveMatchOptions = {
    paths: 'subset',
    queryParams: 'ignored',
    fragment: 'ignored',
    matrixParams: 'ignored',
  };

  protected toggle(): void {
    this.collapsed.update((value) => !value);
  }

  protected navigate(path: string): void {
    this.state.navigateTo(path);
  }

  protected isActive(path: string): boolean {
    return this.router.isActive(path, this.activeMatch);
  }
}

<aside
  class="flex h-full flex-col border-r bg-sidebar transition-all duration-300"
  [class.w-16]="collapsed()"
  [class.w-56]="!collapsed()"
>
  <div class="flex items-center justify-end border-b p-3">
    <button
      type="button"
      class="flex h-8 w-8 items-center justify-center rounded hover:bg-sidebar-accent/60"
      (click)="toggle()"
    >
      <lucide-icon
        name="ChevronLeft"
        class="h-4 w-4 transition-transform"
        [class.rotate-180]="collapsed()"
      />
    </button>
  </div>

  <nav class="flex-1 space-y-1 p-2 text-sm font-medium">
    @for (item of items; track item.id) {
      <button
        type="button"
        class="flex w-full items-center gap-3 rounded px-3 py-2 text-left transition"
        [ngClass]="
          isActive(item.path)
            ? 'bg-sidebar-accent text-sidebar-accent-foreground'
            : 'text-sidebar-foreground hover:bg-sidebar-accent/50'
        "
        (click)="navigate(item.path)"
      >
        <lucide-icon [name]="item.icon" class="h-4 w-4 shrink-0" />
        @if (!collapsed()) {
          <span class="truncate">{{ item.label }}</span>
        }
      </button>
    }

    <div class="my-2 h-px bg-sidebar-border"></div>

    <button
      type="button"
      class="flex w-full items-center gap-3 rounded px-3 py-2 text-left transition"
      [ngClass]="
        isActive(adminItem.path)
          ? 'bg-sidebar-accent text-sidebar-accent-foreground'
          : 'text-sidebar-foreground hover:bg-sidebar-accent/50'
      "
      (click)="navigate(adminItem.path)"
    >
      <lucide-icon [name]="adminItem.icon" class="h-4 w-4 shrink-0" />
      @if (!collapsed()) {
        <span class="truncate">{{ adminItem.label }}</span>
      }
    </button>
  </nav>
</aside>
