// src/app/features/overview/overview.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  DestroyRef,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { RouterModule } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import {
  mock13WeekCashData,
  mockAlerts,
  mockHeadlines,
  mockSections,
} from '../../data/mock-data';
import {
  ApWidgetApiResponse,
  ArWidgetApiResponse,
  GlobalFilters,
  HealthStatus,
  SectionConfig,
} from '../../core/models/dashboard.models';
import { DashboardStateService } from '../../core/services/dashboard-state.service';
import { ArWidgetService } from '../../core/services/ar-widget.service';
import { ApWidgetService } from '../../core/services/ap-widget.service';
import { resolveWidgetWindow } from '../../core/utils/periods';
import {
  formatCurrencyCompact,
  formatDays,
  toDeltaPercent,
} from '../../core/utils/formatters';
import { SparklineComponent } from '../../shared/components/sparkline/sparkline.component';
import { LucideIconsModule } from '../../shared/lucide-icons.module';

interface WidgetState<T> {
  loading: boolean;
  error: string | null;
  data: T | null;
}

@Component({
  selector: 'app-overview',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideIconsModule, SparklineComponent],
  templateUrl: './overview.component.html',
  styleUrl: './overview.component.scss',
})
export class OverviewComponent {
  protected readonly state = inject(DashboardStateService);
  private readonly arService = inject(ArWidgetService);
  private readonly apService = inject(ApWidgetService);
  private readonly destroyRef = inject(DestroyRef);

  protected readonly sections = signal(mockSections);
  protected readonly headlines = mockHeadlines;
  protected readonly alerts = mockAlerts;
  protected readonly cashTrend = mock13WeekCashData;
  protected readonly statusClasses: Record<HealthStatus, string> = {
    healthy: 'border-emerald-200 bg-emerald-50 text-emerald-700',
    warning: 'border-amber-200 bg-amber-50 text-amber-700',
    critical: 'border-red-200 bg-red-50 text-red-700',
  };

  protected readonly arState = signal<WidgetState<ArWidgetApiResponse>>({
    loading: false,
    error: null,
    data: null,
  });

  protected readonly apState = signal<WidgetState<ApWidgetApiResponse>>({
    loading: false,
    error: null,
    data: null,
  });

  protected readonly computedSections = signal<SectionConfig[]>(mockSections);
  protected readonly arSection = computed(() =>
    this.computedSections().find((section) => section.id === 'ar')
  );
  protected readonly apSection = computed(() =>
    this.computedSections().find((section) => section.id === 'ap')
  );

  private readonly widgetEffect = effect(
    () => {
      const filters = this.state.filters();
      this.loadWidgets(filters);
    },
    { allowSignalWrites: true }
  );

  private readonly sectionsEffect = effect(
    () => {
      this.computedSections.set(
        this.sections().map((section) => {
          if (section.id === 'ar') {
            return buildArSection(section, this.arState());
          }
          if (section.id === 'ap') {
            return buildApSection(section, this.apState());
          }
          return section;
        })
      );
    },
    { allowSignalWrites: true }
  );

  protected navigateToSection(sectionId: string): void {
    const path =
      sectionId === 'overview' ? '/overview' : `/sections/${sectionId}`;
    this.state.navigateTo(path);
  }

  private loadWidgets(filters: GlobalFilters): void {
    const payload = buildWidgetPayload(filters);
    if (!payload) {
      this.arState.set({ loading: false, error: null, data: null });
      this.apState.set({ loading: false, error: null, data: null });
      return;
    }

    this.arState.update((current) => ({ ...current, loading: true, error: null }));
    this.apState.update((current) => ({ ...current, loading: true, error: null }));

    this.arService
      .fetchWidget(payload)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (data) => this.arState.set({ loading: false, error: null, data }),
        error: (error) =>
          this.arState.set({
            loading: false,
            error: error.message ?? 'Unable to load Accounts Receivable widget',
            data: null,
          }),
      });

    this.apService
      .fetchWidget(payload)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (data) => this.apState.set({ loading: false, error: null, data }),
        error: (error) =>
          this.apState.set({
            loading: false,
            error: error.message ?? 'Unable to load Accounts Payable widget',
            data: null,
          }),
      });
  }
}

const statusMap: Record<string, HealthStatus> = {
  ok: 'healthy',
  warning: 'warning',
  critical: 'critical',
};

const buildWidgetPayload = (filters: GlobalFilters) => {
  if (!filters.tenant) {
    return null;
  }

  const periodWindow = resolveWidgetWindow(filters.period);
  return {
    tenant: filters.tenant.name,
    entityId: getEntityId(filters),
    mode: periodWindow.mode,
    compare: periodWindow.compare,
    from: periodWindow.from ?? null,
    to: periodWindow.to ?? null,
    reportCcy: filters.entity?.baseCurrency ?? null,
  };
};

const getEntityId = (filters: GlobalFilters): number | null => {
  if (!filters.entity) {
    return null;
  }
  if (filters.entity.directoryEntityId) {
    return filters.entity.directoryEntityId;
  }
  const parsed = Number(filters.entity.id);
  return Number.isFinite(parsed) ? parsed : null;
};

const buildArSection = (
  base: SectionConfig,
  state: WidgetState<ArWidgetApiResponse>
): SectionConfig => {
  if (!state.data) {
    return buildPlaceholderSection(base, state);
  }

  const { status, status_reason, metrics, source, filters } = state.data;
  const [dsoBase = { label: 'DSO', value: '--' }, openArBase = { label: 'Open AR', value: '--' }] =
    base.kpis;

  return {
    ...base,
    status: statusMap[status] ?? base.status,
    statusReason: status_reason,
    source: source ?? base.source,
    kpis: [
      {
        ...dsoBase,
        value: formatDays(metrics.dso.value_days),
        change: toDeltaPercent(metrics.dso.delta_pct),
        trend: resolveTrend(metrics.dso.delta_pct),
      },
      {
        ...openArBase,
        value: formatCurrencyCompact(
          metrics.open_ar.value,
          metrics.open_ar.currency || filters.report_ccy || 'USD'
        ),
        change: toDeltaPercent(metrics.open_ar.delta_pct),
        trend: resolveTrend(metrics.open_ar.delta_pct),
      },
    ],
  };
};

const buildApSection = (
  base: SectionConfig,
  state: WidgetState<ApWidgetApiResponse>
): SectionConfig => {
  if (!state.data) {
    return buildPlaceholderSection(base, state);
  }

  const { status, status_reason, metrics, source, filters } = state.data;
  const [dpoBase = { label: 'DPO', value: '--' }, openApBase = { label: 'Open AP', value: '--' }] =
    base.kpis;

  return {
    ...base,
    status: statusMap[status] ?? base.status,
    statusReason: status_reason,
    source: source ?? base.source,
    kpis: [
      {
        ...dpoBase,
        value: formatDays(metrics.dpo.value_days),
        change: toDeltaPercent(metrics.dpo.delta_pct),
        trend: resolveTrend(metrics.dpo.delta_pct),
      },
      {
        ...openApBase,
        value: formatCurrencyCompact(
          metrics.open_ap.value,
          metrics.open_ap.currency || filters.report_ccy || 'USD'
        ),
        change: toDeltaPercent(metrics.open_ap.delta_pct),
        trend: resolveTrend(metrics.open_ap.delta_pct),
      },
    ],
  };
};

const buildPlaceholderSection = <T>(
  base: SectionConfig,
  state: WidgetState<T>
): SectionConfig => ({
  ...base,
  status: state.error ? 'critical' : base.status,
  statusReason: state.error ?? base.statusReason,
  kpis: base.kpis.map((kpi) => ({
    ...kpi,
    value: state.loading ? 'Loading...' : '--',
    change: undefined,
    trend: undefined,
  })),
});

const resolveTrend = (delta?: number | null): 'up' | 'down' | undefined => {
  if (delta === null || delta === undefined) {
    return undefined;
  }
  return delta >= 0 ? 'up' : 'down';
};

<section class="space-y-6">
  <div class="grid gap-4 lg:grid-cols-3">
    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">Current Context</p>
          <h2 class="text-lg font-semibold">Executive Overview</h2>
        </div>
        <lucide-icon name="LayoutDashboard" class="h-5 w-5 text-primary" />
      </div>
      <dl class="mt-4 space-y-2 text-sm">
        <div class="flex justify-between">
          <dt class="text-muted-foreground">Tenant</dt>
          <dd class="font-medium">
            {{ state.filters().tenant?.name ?? 'Not Selected' }}
          </dd>
        </div>
        <div class="flex justify-between">
          <dt class="text-muted-foreground">Entity</dt>
          <dd class="font-medium">
            {{ state.filters().entity?.name ?? 'All' }}
          </dd>
        </div>
        <div class="flex justify-between">
          <dt class="text-muted-foreground">Period</dt>
          <dd class="font-medium">{{ state.filters().period.label }}</dd>
        </div>
      </dl>
      <div class="mt-4 rounded-lg bg-muted p-3 text-xs text-muted-foreground">
        Right-click anywhere to copy direct deep links with filters applied.
      </div>
    </div>

    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">Signals</p>
          <h2 class="text-lg font-semibold">Headlines</h2>
        </div>
        <lucide-icon name="Bell" class="h-5 w-5 text-primary" />
      </div>
      <ul class="mt-4 space-y-3 text-sm">
        @for (headline of headlines; track headline.label) {
          <li class="flex items-center justify-between rounded-lg border border-dashed border-border px-3 py-2">
            <div>
              <p class="text-muted-foreground">{{ headline.label }}</p>
              <p class="font-semibold">{{ headline.value }}</p>
            </div>
            <lucide-icon
              [name]="headline.trend === 'down' ? 'ArrowDown' : 'ArrowUp'"
              class="h-4 w-4"
              [class.text-emerald-500]="headline.trend === 'up'"
              [class.text-red-500]="headline.trend === 'down'"
            />
          </li>
        }
      </ul>
    </div>

    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">Open Alerts</p>
          <h2 class="text-lg font-semibold">
            {{ state.unreadAlerts() }} awaiting review
          </h2>
        </div>
        <button
          type="button"
          class="rounded-full border border-border px-3 py-1 text-xs font-medium transition hover:bg-muted"
          (click)="navigateToSection('alerts')"
        >
          View all
        </button>
      </div>
      <ul class="mt-4 space-y-3 text-sm">
        @for (alert of alerts | slice:0:3; track alert.id) {
          <li class="cursor-pointer rounded-lg border border-border/60 p-3 hover:border-border" (click)="navigateToSection(alert.section)">
            <div class="flex items-center justify-between">
              <span
                class="rounded-full px-2 py-0.5 text-xs font-medium"
                [class.bg-red-50]="alert.severity === 'high'"
                [class.text-red-600]="alert.severity === 'high'"
                [class.bg-amber-50]="alert.severity === 'medium'"
                [class.text-amber-600]="alert.severity === 'medium'"
                [class.bg-blue-50]="alert.severity === 'low'"
                [class.text-blue-600]="alert.severity === 'low'"
              >
                {{ alert.severity | titlecase }}
              </span>
              <span class="text-xs text-muted-foreground">
                {{ alert.timestamp | date: 'shortTime' }}
              </span>
            </div>
            <p class="mt-2 font-medium">{{ alert.title }}</p>
            <p class="text-xs text-muted-foreground">
              {{ alert.description }}
            </p>
          </li>
        }
      </ul>
    </div>
  </div>

  <div class="grid gap-4 lg:grid-cols-2">
    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">Accounts Receivable</p>
          <h2 class="text-lg font-semibold">Collection Efficiency</h2>
        </div>
        <span class="text-xs text-muted-foreground">
          @if (arState().loading) {
            Loading...
          } @else if (arState().error) {
            Error
          } @else {
            Synced
          }
        </span>
      </div>

      <div class="mt-4 flex flex-wrap gap-2 text-xs">
        <span class="rounded-full border px-3 py-1 font-medium" [ngClass]="statusClasses[arSection()?.status ?? 'healthy']">
          {{ arSection()?.status | titlecase }}
        </span>
        @if (arSection()?.statusReason) {
          <span class="rounded-full bg-muted px-3 py-1 text-muted-foreground">
            {{ arSection()?.statusReason }}
          </span>
        }
      </div>

      <div class="mt-4 grid gap-4 sm:grid-cols-2">
        @for (kpi of arSection()?.kpis ?? []; track kpi.label) {
          <div class="rounded-xl border border-border/70 p-3">
            <p class="text-xs text-muted-foreground">{{ kpi.label }}</p>
            <p class="text-xl font-semibold">{{ kpi.value }}</p>
            @if (kpi.change !== undefined) {
              <p class="mt-1 text-xs" [class.text-emerald-600]="kpi.trend === 'up'" [class.text-red-600]="kpi.trend === 'down'">
                <lucide-icon
                  [name]="kpi.trend === 'down' ? 'ArrowDown' : 'ArrowUp'"
                  class="mr-1 inline h-3 w-3"
                />
                {{ kpi.change }}%
              </p>
            }
          </div>
        }
      </div>

      @if (arState().error) {
        <p class="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-600">
          {{ arState().error }}
        </p>
      }
    </div>

    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">Accounts Payable</p>
          <h2 class="text-lg font-semibold">Disbursement Health</h2>
        </div>
        <span class="text-xs text-muted-foreground">
          @if (apState().loading) {
            Loading...
          } @else if (apState().error) {
            Error
          } @else {
            Synced
          }
        </span>
      </div>

      <div class="mt-4 flex flex-wrap gap-2 text-xs">
        <span class="rounded-full border px-3 py-1 font-medium" [ngClass]="statusClasses[apSection()?.status ?? 'healthy']">
          {{ apSection()?.status | titlecase }}
        </span>
        @if (apSection()?.statusReason) {
          <span class="rounded-full bg-muted px-3 py-1 text-muted-foreground">
            {{ apSection()?.statusReason }}
          </span>
        }
      </div>

      <div class="mt-4 grid gap-4 sm:grid-cols-2">
        @for (kpi of apSection()?.kpis ?? []; track kpi.label) {
          <div class="rounded-xl border border-border/70 p-3">
            <p class="text-xs text-muted-foreground">{{ kpi.label }}</p>
            <p class="text-xl font-semibold">{{ kpi.value }}</p>
            @if (kpi.change !== undefined) {
              <p class="mt-1 text-xs" [class.text-emerald-600]="kpi.trend === 'up'" [class.text-red-600]="kpi.trend === 'down'">
                <lucide-icon
                  [name]="kpi.trend === 'down' ? 'ArrowDown' : 'ArrowUp'"
                  class="mr-1 inline h-3 w-3"
                />
                {{ kpi.change }}%
              </p>
            }
          </div>
        }
      </div>

      @if (apState().error) {
        <p class="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-600">
          {{ apState().error }}
        </p>
      }
    </div>
  </div>

  <div class="grid gap-4 xl:grid-cols-3">
    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">Cash Projection</p>
          <h2 class="text-lg font-semibold">13-Week Outlook</h2>
        </div>
        <span class="text-xs text-muted-foreground">USD (millions)</span>
      </div>
      <div class="mt-4 space-y-2 text-sm">
        @for (point of cashTrend; track point.week) {
          <div class="flex items-center justify-between rounded border border-dashed border-border px-3 py-2">
            <span class="text-muted-foreground">{{ point.week }}</span>
            <span class="font-medium">
              {{ point.actual ?? point.projected }}M
              <span class="text-xs text-muted-foreground">
                {{ point.actual ? 'actual' : 'projected' }}
              </span>
            </span>
          </div>
        }
      </div>
    </div>

    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">AI Insights</p>
          <h2 class="text-lg font-semibold">Explainability</h2>
        </div>
        <lucide-icon name="Sparkles" class="h-5 w-5 text-primary" />
      </div>
      <p class="mt-4 text-sm text-muted-foreground">
        Enable AI Explain to receive contextual narratives, root-cause analysis, and sharing
        controls directly in the workspace. Insights adapt to the filters you set above.
      </p>
      <button
        type="button"
        class="mt-4 w-full rounded-lg border border-border px-4 py-2 text-sm font-medium transition hover:bg-muted"
        (click)="state.toggleAiInsights()"
      >
        {{ state.aiEnabled() ? 'Disable' : 'Enable' }} AI Explain
      </button>
    </div>

    <div class="rounded-2xl border border-border bg-card p-4 shadow-card">
      <div class="flex items-center justify-between">
        <div>
          <p class="text-sm text-muted-foreground">Quick Links</p>
          <h2 class="text-lg font-semibold">Deep Dives</h2>
        </div>
        <lucide-icon name="ChevronRight" class="h-5 w-5 text-primary" />
      </div>
      <ul class="mt-4 space-y-2 text-sm">
        <li
          class="flex cursor-pointer items-center justify-between rounded-lg border border-border px-3 py-2 hover:bg-muted"
          (click)="navigateToSection('ar')"
        >
          <span>Overdue invoices</span>
          <lucide-icon name="ArrowRight" class="h-4 w-4" />
        </li>
        <li
          class="flex cursor-pointer items-center justify-between rounded-lg border border-border px-3 py-2 hover:bg-muted"
          (click)="navigateToSection('fx-treasury')"
        >
          <span>FX exposure</span>
          <lucide-icon name="ArrowRight" class="h-4 w-4" />
        </li>
        <li
          class="flex cursor-pointer items-center justify-between rounded-lg border border-border px-3 py-2 hover:bg-muted"
          (click)="navigateToSection('concentration-risk')"
        >
          <span>Concentration limits</span>
          <lucide-icon name="ArrowRight" class="h-4 w-4" />
        </li>
      </ul>
    </div>
  </div>

  <div class="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">
    @for (section of computedSections(); track section.id) {
      <article
        class="flex cursor-pointer flex-col rounded-2xl border border-border bg-card p-4 shadow-card transition hover:border-primary"
        (click)="navigateToSection(section.id)"
      >
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm text-muted-foreground">{{ section.name }}</p>
            <h3 class="text-xl font-semibold">
              {{ section.kpis.length ? section.kpis[0].value : '--' }}
            </h3>
          </div>
          <span
            class="rounded-full border px-3 py-1 text-xs font-medium"
            [ngClass]="statusClasses[section.status]"
          >
            {{ section.status | titlecase }}
          </span>
        </div>
        <div class="mt-4 grid gap-3 text-sm text-muted-foreground">
          @for (kpi of section.kpis; track kpi.label) {
            <div class="flex items-center justify-between">
              <span>{{ kpi.label }}</span>
              <span class="font-semibold text-foreground">{{ kpi.value }}</span>
            </div>
          }
        </div>
        @if (section.sparklineData?.length) {
          <div class="mt-4">
            <app-sparkline [data]="section.sparklineData!" />
          </div>
        }
      </article>
    }
  </div>
</section>

// src/components/overview/Overview.tsx
import { useEffect, useMemo, useState } from 'react';
import { Card } from '../ui/card';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import {
  LineChart,
  Line,
  ResponsiveContainer,
} from 'recharts';
import {
  Droplets,
  ArrowDownToLine,
  ArrowUpToLine,
  TrendingUp,
  Repeat,
  DollarSign,
  Coins,
  FileText,
  Scale,
  Target,
  Bell,
  Settings,
  ChevronRight,
  ArrowUp,
  ArrowDown,
} from 'lucide-react';
import { mockSections, mockHeadlines } from '../../lib/mockData';
import { cn } from '../ui/utils';
import {
  ArWidgetApiResponse,
  ApWidgetApiResponse,
  WidgetRequestPayload,
  GlobalFilters,
  HealthStatus,
  SectionConfig,
} from '../../types';
import { arWidgetService } from '../../services/api/arWidgetService';
import { apWidgetService } from '../../services/api/apWidgetService';
import { resolveWidgetWindow } from '../../lib/periods';
import {
  formatCurrencyCompact,
  formatDays,
  toDeltaPercent,
} from '../../lib/formatters';

interface OverviewProps {
  filters: GlobalFilters;
  onNavigateToSection: (sectionId: string) => void;
}

const iconMap: Record<string, any> = {
  Droplets,
  ArrowDownToLine,
  ArrowUpToLine,
  TrendingUp,
  Repeat,
  DollarSign,
  Coins,
  FileText,
  Scale,
  Target,
  Bell,
  Settings,
};

const statusColors: Record<HealthStatus, string> = {
  healthy: 'bg-green-500/20 border-green-500',
  warning: 'bg-yellow-500/20 border-yellow-500',
  critical: 'bg-red-500/20 border-red-500',
};

const statusBadgeColors: Record<HealthStatus, 'default' | 'secondary' | 'destructive'> = {
  healthy: 'default',
  warning: 'secondary',
  critical: 'destructive',
};

function MiniSparkline({ data }: { data: number[] }) {
  const chartData = data.map((value, index) => ({ x: index, y: value }));
  
  return (
    <ResponsiveContainer width="100%" height={32}>
      <LineChart data={chartData}>
        <Line
          type="monotone"
          dataKey="y"
          stroke="currentColor"
          strokeWidth={1.5}
          dot={false}
        />
      </LineChart>
    </ResponsiveContainer>
  );
}

export function Overview({ filters, onNavigateToSection }: OverviewProps) {
  const [arWidget, setArWidget] = useState<ArWidgetApiResponse | null>(null);
  const [arLoading, setArLoading] = useState(false);
  const [arError, setArError] = useState<string | null>(null);
  const [apWidget, setApWidget] = useState<ApWidgetApiResponse | null>(null);
  const [apLoading, setApLoading] = useState(false);
  const [apError, setApError] = useState<string | null>(null);

  const widgetPayload = useMemo(
    () => buildWidgetPayload(filters),
    [
      filters.tenant?.id,
      filters.tenant?.name,
      filters.entity?.id,
      filters.entity?.directoryEntityId,
      filters.entity?.baseCurrency,
      filters.period.id,
      filters.period.type,
    ]
  );

  useEffect(() => {
    if (!widgetPayload) {
      setArWidget(null);
      setArError(null);
      setArLoading(false);
      return;
    }

    let active = true;
    const controller = new AbortController();
    setArLoading(true);
    setArError(null);

    arWidgetService
      .fetchWidget(widgetPayload, controller.signal)
      .then((data) => {
        if (!active) return;
        setArWidget(data);
      })
      .catch((error) => {
        if (!active || error.name === 'AbortError') return;
        console.error('Failed to load Accounts Receivable widget', error);
        setArError('Unable to load Accounts Receivable');
      })
      .finally(() => {
        if (active) {
          setArLoading(false);
        }
      });

    return () => {
      active = false;
      controller.abort();
    };
  }, [widgetPayload]);

  useEffect(() => {
    if (!widgetPayload) {
      setApWidget(null);
      setApError(null);
      setApLoading(false);
      return;
    }

    let active = true;
    const controller = new AbortController();
    setApLoading(true);
    setApError(null);

    apWidgetService
      .fetchWidget(widgetPayload, controller.signal)
      .then((data) => {
        if (!active) return;
        setApWidget(data);
      })
      .catch((error) => {
        if (!active || error.name === 'AbortError') return;
        console.error('Failed to load Accounts Payable widget', error);
        setApError('Unable to load Accounts Payable');
      })
      .finally(() => {
        if (active) {
          setApLoading(false);
        }
      });

    return () => {
      active = false;
      controller.abort();
    };
  }, [widgetPayload]);

  const sections = useMemo(
    () =>
      mockSections.map((section) =>
        section.id === 'ar'
          ? buildArSection(section, { data: arWidget, loading: arLoading, error: arError })
          : section.id === 'ap'
            ? buildApSection(section, { data: apWidget, loading: apLoading, error: apError })
          : section
      ),
    [arWidget, arLoading, arError, apWidget, apLoading, apError]
  );

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2>Dashboard</h2>
          <p className="text-muted-foreground">Executive business health overview</p>
        </div>
        <Button size="sm">
          Export Report
        </Button>
      </div>
      {/* Headlines */}
      <div className="grid gap-4 md:grid-cols-3" style={{ display: 'none' }}>
        {mockHeadlines.map((headline, index) => (
          <Card key={index} className="p-4">
            <p className="mb-2 text-muted-foreground">{headline.label}</p>
            <div className="flex items-center gap-2">
              <span className="text-2xl">{headline.value}</span>
              {headline.trend === 'up' ? (
                <ArrowUp className="h-4 w-4 text-green-500" />
              ) : (
                <ArrowDown className="h-4 w-4 text-red-500" />
              )}
            </div>
          </Card>
        ))}
      </div>

      {/* Section Cards */}
      <div>
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {sections.map((section) => {
            const Icon = iconMap[section.icon];
            return (
              <Card
                key={section.id}
                className="group cursor-pointer transition-all hover:shadow-lg"
                onClick={() => onNavigateToSection(section.id)}
              >
                <div className="p-4">
                  <div className="mb-3 flex items-start justify-between">
                    <div className="flex items-center gap-2">
                      <div className={cn(
                        'rounded-lg p-2',
                        section.status === 'healthy' && 'bg-green-500/10',
                        section.status === 'warning' && 'bg-yellow-500/10',
                        section.status === 'critical' && 'bg-red-500/10'
                      )}>
                        <Icon className="h-4 w-4" />
                      </div>
                      <Badge variant={statusBadgeColors[section.status]}>
                        {section.status}
                      </Badge>
                    </div>
                    <ChevronRight className="h-4 w-4 text-muted-foreground transition-transform group-hover:translate-x-1" />
                  </div>

                  <h4 className="mb-3">{section.name}</h4>

                  <div className="space-y-2">
                    {section.kpis.map((kpi, idx) => (
                      <div key={idx}>
                        <p className="text-muted-foreground">{kpi.label}</p>
                        <div className="flex items-center gap-2">
                          <span className="text-xl">{kpi.value}</span>
                          {kpi.change !== undefined && (
                            <span
                              className={cn(
                                'flex items-center gap-0.5',
                                kpi.trend === 'up' ? 'text-green-500' : 'text-red-500'
                              )}
                            >
                              {kpi.trend === 'up' ? (
                                <ArrowUp className="h-3 w-3" />
                              ) : (
                                <ArrowDown className="h-3 w-3" />
                              )}
                              {Math.abs(kpi.change)}%
                            </span>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>

                  {section.statusReason && (
                    <p className="mt-3 text-sm text-muted-foreground">
                      {section.statusReason}
                    </p>
                  )}

                  {section.sparklineData && (
                    <div className="mt-4 h-12 opacity-60">
                      <MiniSparkline data={section.sparklineData} />
                    </div>
                  )}

                  <div className="mt-3 text-muted-foreground">
                    Source: {section.source ?? `api_${section.id}`}
                  </div>
                </div>
              </Card>
            );
          })}
        </div>
      </div>
    </div>
  );
}

type WidgetStatus = 'ok' | 'warning' | 'critical';

const statusMap: Record<WidgetStatus, HealthStatus> = {
  ok: 'healthy',
  warning: 'warning',
  critical: 'critical',
};

const buildWidgetPayload = (
  filters: GlobalFilters
): WidgetRequestPayload | null => {
  if (!filters.tenant || !filters.period) {
    return null;
  }

  const window = resolveWidgetWindow(filters.period);
  const entityId = getEntityId(filters);

  return {
    tenant: filters.tenant.name,
    entityId,
    mode: window.mode,
    from: window.from ?? null,
    to: window.to ?? null,
    compare: window.compare,
    reportCcy: filters.entity?.baseCurrency ?? null,
  };
};

const getEntityId = (filters: GlobalFilters): number | null => {
  if (!filters.entity) {
    return null;
  }

  if (filters.entity.directoryEntityId) {
    return filters.entity.directoryEntityId;
  }

  const parsed = Number(filters.entity.id);
  return Number.isFinite(parsed) ? parsed : null;
};

const buildArSection = (
  base: SectionConfig,
  state: {
    data: ArWidgetApiResponse | null;
    loading: boolean;
    error: string | null;
  }
): SectionConfig => {
  if (!state.data) {
    return {
      ...base,
      status: state.error ? 'critical' : base.status,
      statusReason: state.error ?? base.statusReason,
      kpis: base.kpis.map((kpi) => ({
        ...kpi,
        value: state.loading ? 'Loading...' : '--',
        change: undefined,
        trend: undefined,
      })),
    };
  }

  const { status, status_reason, metrics, source, filters } = state.data;
  const [dsoBase = { label: 'DSO', value: '--' }, openArBase = { label: 'Open AR', value: '--' }] =
    base.kpis;

  const dsoSection = {
    ...dsoBase,
    value: formatDays(metrics.dso.value_days),
    change: toDeltaPercent(metrics.dso.delta_pct),
    trend: resolveTrend(metrics.dso.delta_pct),
  };

  const currency =
    metrics.open_ar.currency || filters.report_ccy || 'USD';

  const openArSection = {
    ...openArBase,
    value: formatCurrencyCompact(metrics.open_ar.value, currency),
    change: toDeltaPercent(metrics.open_ar.delta_pct),
    trend: resolveTrend(metrics.open_ar.delta_pct),
  };

  return {
    ...base,
    status: statusMap[status] ?? base.status,
    statusReason: status_reason,
    source: source ?? base.source,
    kpis: [dsoSection, openArSection],
  };
};

const buildApSection = (
  base: SectionConfig,
  state: {
    data: ApWidgetApiResponse | null;
    loading: boolean;
    error: string | null;
  }
): SectionConfig => {
  if (!state.data) {
    return {
      ...base,
      status: state.error ? 'critical' : base.status,
      statusReason: state.error ?? base.statusReason,
      kpis: base.kpis.map((kpi) => ({
        ...kpi,
        value: state.loading ? 'Loading...' : '--',
        change: undefined,
        trend: undefined,
      })),
    };
  }

  const { status, status_reason, metrics, source, filters } = state.data;
  const [dpoBase = { label: 'DPO', value: '--' }, openApBase = { label: 'Open AP', value: '--' }] =
    base.kpis;

  const dpoSection = {
    ...dpoBase,
    value: formatDays(metrics.dpo.value_days),
    change: toDeltaPercent(metrics.dpo.delta_pct),
    trend: resolveTrend(metrics.dpo.delta_pct),
  };

  const currency =
    metrics.open_ap.currency || filters.report_ccy || 'USD';

  const openApSection = {
    ...openApBase,
    value: formatCurrencyCompact(metrics.open_ap.value, currency),
    change: toDeltaPercent(metrics.open_ap.delta_pct),
    trend: resolveTrend(metrics.open_ap.delta_pct),
  };

  return {
    ...base,
    status: statusMap[status] ?? base.status,
    statusReason: status_reason,
    source: source ?? base.source,
    kpis: [dpoSection, openApSection],
  };
};

const resolveTrend = (
  delta?: number | null
): 'up' | 'down' | undefined => {
  if (delta === null || delta === undefined) {
    return undefined;
  }
  return delta >= 0 ? 'up' : 'down';
};
