// src/components/layout/RightDrawer.tsx
import { X, Sparkles, Share2, GitBranch } from 'lucide-react';
import { Button } from '../ui/button';
import { ScrollArea } from '../ui/scroll-area';
import { Badge } from '../ui/badge';
import { Separator } from '../ui/separator';

interface RightDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  section?: string;
  context?: string;
}

export function RightDrawer({ isOpen, onClose, section, context }: RightDrawerProps) {
  if (!isOpen) return null;

  const narratives: Record<string, string> = {
    overview: 'Overall business health is strong with 9 of 12 sections showing healthy status. Key concerns: AR days sales outstanding has increased to 42 days (up 3 days MoM), and customer concentration risk now exceeds policy thresholds at 58% from top 5 customers. FX exposure hedge ratio has dropped to 62%, below the 70% target. Cash position remains solid at $24.3M with projected growth to $30.1M over the next 13 weeks.',
    ar: 'Accounts Receivable DSO has increased to 42 days, 7 days above target. Open AR stands at $8.2M with 15 invoices totaling $680K now over 60 days overdue. Top 3 customers represent $4.2M (51% of total AR). Collection efficiency has declined 8% this month. Recommend immediate focus on overdue accounts, particularly Enterprise Account #1247 ($380K, 72 days overdue).',
    liquidity: 'Cash position is healthy at $24.3M, up 8.2% from last month. Quick ratio improved to 2.4x from 2.1x. 13-week cash projection shows steady growth to $30.1M driven by expected Q4 collections and new contract advances. No liquidity concerns identified. Cash concentration: 62% in operating accounts, 38% in treasury instruments yielding 4.8%.',
  };

  const apiSources: Record<string, string[]> = {
    overview: ['api_board_pack', 'api_ai_bundle', 'api_health_summary'],
    ar: ['api_ar_aging_summary', 'api_ar_overdue_list', 'api_ar_top_customers', 'api_ar_soa'],
    liquidity: ['api_cash_position', 'api_cash_projection_13w', 'api_liquidity_ratios'],
  };

  const narrative = narratives[section || 'overview'] || 'AI analysis will appear here based on the current view and filters.';
  const sources = apiSources[section || 'overview'] || ['api_generic'];

  return (
    <div className="fixed right-0 top-0 z-50 h-full w-96 border-l bg-card shadow-lg">
      <div className="flex items-center justify-between border-b px-4 py-3">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-primary" />
          <span>AI Insights</span>
        </div>
        <Button variant="ghost" size="icon" onClick={onClose}>
          <X className="h-4 w-4" />
        </Button>
      </div>

      <ScrollArea className="h-[calc(100%-4rem)]">
        <div className="space-y-6 p-4">
          {/* Narrative */}
          <div>
            <div className="mb-2 flex items-center gap-2">
              <Sparkles className="h-3.5 w-3.5 text-muted-foreground" />
              <span className="text-muted-foreground">Explain This</span>
            </div>
            <p className="leading-relaxed">{narrative}</p>
          </div>

          <Separator />

          {/* Data Sources */}
          <div>
            <div className="mb-3 flex items-center gap-2">
              <GitBranch className="h-3.5 w-3.5 text-muted-foreground" />
              <span className="text-muted-foreground">Data Sources</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {sources.map((source) => (
                <Badge key={source} variant="outline">
                  {source}
                </Badge>
              ))}
            </div>
          </div>

          <Separator />

          {/* Why Different from ERP */}
          <div>
            <h4 className="mb-2 text-muted-foreground">Why Different from ERP?</h4>
            <p className="leading-relaxed text-muted-foreground">
              This dashboard applies normalization rules, consolidation logic, and FX adjustments
              that may differ from raw ERP outputs. Data lineage includes ETL transformations
              applied on {new Date().toLocaleDateString()}.
            </p>
          </div>

          <Separator />

          {/* Share View */}
          <div>
            <Button variant="outline" className="w-full gap-2">
              <Share2 className="h-4 w-4" />
              Share This View
            </Button>
            <p className="mt-2 text-muted-foreground">
              Generate a deep link with current filters locked
            </p>
          </div>

          {/* Last Refresh */}
          <div className="rounded-lg bg-muted p-3">
            <p className="text-muted-foreground">
              Last refresh: <span className="text-foreground">2 minutes ago</span>
            </p>
            <p className="mt-1 text-muted-foreground">
              Next scheduled: <span className="text-foreground">in 28 minutes</span>
            </p>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}

// src/app/layout/right-drawer/right-drawer.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { LucideIconsModule } from '../../shared/lucide-icons.module';

@Component({
  selector: 'app-right-drawer',
  standalone: true,
  imports: [CommonModule, LucideIconsModule],
  templateUrl: './right-drawer.component.html',
  styleUrl: './right-drawer.component.scss',
})
export class RightDrawerComponent {
  @Input() open = false;
  @Input() section = 'overview';
  @Input() context = '';
  @Output() closed = new EventEmitter<void>();
  protected readonly today = new Date();

  protected readonly narratives: Record<string, string> = {
    overview:
      'Overall business health is strong with 9 of 12 sections showing healthy status. Key concerns include higher AR DSO, increased concentration risk, and a lower hedge ratio. Cash position remains solid at $24.3M with projected growth over the next 13 weeks.',
    ar: 'Accounts Receivable DSO has increased to 42 days, 7 days above target. Open AR stands at $8.2M with 15 invoices totaling $680K more than 60 days overdue. Focus collections on Enterprise Account #1247 and the top three overdue customers representing $4.2M (51% of total AR).',
    liquidity:
      'Cash position is healthy at $24.3M, up 8.2% from last month. Quick ratio improved to 2.4x. 13-week projection shows steady growth to $30.1M supported by expected Q4 collections and new contract advances.',
  };

  protected readonly apiSources: Record<string, string[]> = {
    overview: ['api_board_pack', 'api_ai_bundle', 'api_health_summary'],
    ar: [
      'api_ar_aging_summary',
      'api_ar_overdue_list',
      'api_ar_top_customers',
      'api_ar_soa',
    ],
    liquidity: [
      'api_cash_position',
      'api_cash_projection_13w',
      'api_liquidity_ratios',
    ],
  };

  protected close(): void {
    this.closed.emit();
  }

  protected get narrative(): string {
    return (
      this.narratives[this.section] ??
      'AI analysis will appear here based on the current view and filters.'
    );
  }

  protected get sources(): string[] {
    return this.apiSources[this.section] ?? ['api_generic'];
  }
}

@if (open) {
  <section class="right-drawer">
    <div class="flex items-center justify-between border-b px-4 py-3">
      <div class="flex items-center gap-2 text-sm font-medium">
        <lucide-icon name="Sparkles" class="h-4 w-4 text-primary" />
        <span>AI Insights</span>
      </div>
      <button
        type="button"
        class="rounded-full p-1 text-muted-foreground transition hover:bg-muted"
        (click)="close()"
      >
        <lucide-icon name="X" class="h-4 w-4" />
      </button>
    </div>

    <div class="drawer-scroll">
      <div class="space-y-6 p-4 text-sm leading-relaxed">
        <div>
          <div class="mb-2 flex items-center gap-2 text-muted-foreground">
            <lucide-icon name="Sparkles" class="h-3.5 w-3.5" />
            <span>Explain This</span>
          </div>
          <p>{{ narrative }}</p>
          @if (context) {
            <p class="mt-2 text-xs text-muted-foreground">
              Context: {{ context }}
            </p>
          }
        </div>

        <hr />

        <div>
          <div class="mb-2 flex items-center gap-2 text-muted-foreground">
            <lucide-icon name="GitBranch" class="h-3.5 w-3.5" />
            <span>Data Sources</span>
          </div>
          <div class="flex flex-wrap gap-2">
            @for (source of sources; track source) {
              <span class="rounded-full border px-3 py-1 text-xs">
                {{ source }}
              </span>
            }
          </div>
        </div>

        <hr />

        <div>
          <h4 class="mb-2 text-muted-foreground">Why Different from ERP?</h4>
          <p class="text-muted-foreground">
            This dashboard applies normalization rules, consolidation logic, and
            FX adjustments that may differ from raw ERP outputs. Lineage updated
            on {{ (today | date: 'mediumDate') || 'Today' }}.
          </p>
        </div>

        <hr />

        <div>
          <button
            type="button"
            class="flex w-full items-center justify-center gap-2 rounded border border-border px-4 py-2 text-sm font-medium transition hover:bg-muted"
          >
            <lucide-icon name="Share2" class="h-4 w-4" />
            Share This View
          </button>
          <p class="mt-2 text-muted-foreground">
            Generate a deep link with current filters locked.
          </p>
        </div>

        <div class="rounded-lg bg-muted p-3 text-muted-foreground">
          <p>
            Last refresh: <span class="text-foreground">2 minutes ago</span>
          </p>
          <p class="mt-1">
            Next scheduled: <span class="text-foreground">in 28 minutes</span>
          </p>
        </div>
      </div>
    </div>
  </section>
}
